# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: rootedreasoning
email: rootedreasoning@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  rootedreasoning.com is intended to be a resource for those seeking answers. We believe these 
  answers are rooted in what God has revealed to humans through His nature and His Word. This 
  website maps out the big questions pertaining to this hope and this life, and provides organized, 
  succinct responses to those questions.
baseurl: "/rootedreasoning" # the subpath of your site, e.g. /blog
url: "https://byhag.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# formatted for scss
body-font: Open Sans
title-font: Roboto Slab

# Build settings
exclude: [README.md]
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
collections:
  articles:
    output: true